import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { motion } from "framer-motion"


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <motion.h1 animate={{ scale: 1.1}} transition={{repeat: Infinity, repeatType: "reverse", duration: 1.0 }} className={styles.title}>
          Animate React Apps <span>like a pro</span>
        </motion.h1>

        <p>Adding animations to your web apps take a lot of work.</p>

        <p>You have to account for performance, the type of animations.</p>

        <p>Ask yourself questions like:</p>

        <p>Is it smooth?</p>

        <p>Is it realistic?</p>

        <p>Does it "bounce" too much?</p>
      </main>
    
    </div>
  )
}
